version: '3.4'

services:
  api:
    image: permissionsapi
    build:
      context: ./PermissionsAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    image: permissionsapp
    build:
      context: ./permissions-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
